### ISSUE TITLE
Athenz installation/setup problem: starting athenz ui

### ISSUE THREAD

**Issue by claudiarmamede** [AthenZ/athenz#1730]
Hi!
I'm trying to setup athenz-ui, following these [instructions](https://github.com/AthenZ/athenz/blob/master/docs/setup_ui.md).
I run these commands: 
```
$ export UI_SERVER=localhost ZMS_SERVER=localhost NODE_ENV=production
$ sudo -E bin/athenz_ui start
```
but keep getting the following ui.out:
```
nohup: failed to run command 'NODE_ENV=production': No such file or directory
```
Im using Ubuntu (VERSION="20.04.3 LTS (Focal Fossa)")

Any idea on how to solve this? Thanks in advance

**Comment by havetisyan** [comment]
Hi @claudiarmamede 

Try the following. modify bin/athenz_ui script, search for the following line:

`        nohup NODE_ENV=production nodemon -r dotenv/config app.js > "$log" 2>&1 < /dev/null &
`

and remove the NODE_ENV=production part since that's already set as part of your export command.

**Comment by havetisyan** [comment]
also, I noticed the documentation says 12.x, but you should run it with node js 14.x. (we don't yet support newer versions so I'd stick with 14.x for now).

**Comment by havetisyan** [comment]
@claudiarmamede 

just fyi, we looked at all the manual development documentation and noticed it was missing some steps and had to apply some fix to accommodate for some of the new features we've added since the docs were written. So I suggest to checkout the latest code, build and deploy based on the latest source version since the steps have been verified.
