### ISSUE TITLE
zts java client - Update jackson-databind to get rid of CVE-2020-36518

### ISSUE THREAD

**Issue by nicoloboschi** [AthenZ/athenz#1824]
At the moment if you a user has a dependency to 
```
<dependency>
      <groupId>com.yahoo.athenz</groupId>
      <artifactId>athenz-zts-java-client</artifactId>
</dependency>
```
and it runs the OWASP dependency check it fails because jackson-databind 2.13.1 has a critical vulnerability https://nvd.nist.gov/vuln/detail/CVE-2020-36518

Since it is a fat-jar it would be better to release a CVE-free jar

Note: the safe version is 12.13.2.1

**Comment by havetisyan** [comment]
Hi @nicoloboschi 

I was hoping for a complete 2.13.3 release to keep the versions consistent but only databind was updated. Anyway, we'll probably have a release later on today with the updated version.

However, I strongly discourage the use of the  uber jar in your application. Unless it's using jersey 1.x instead of jersey 2.x which is used by athenz libs (the reason why the fat jar was created), I'd recommend updating your service to use the core zts client:

`
<dependency>
      <groupId>com.yahoo.athenz</groupId>
      <artifactId>athenz-zts-java-client-core</artifactId>
</dependency>
`

**Comment by nicoloboschi** [comment]
Thanks @havetisyan. We moved to the regular jar
