### ISSUE TITLE
It looks like the breaking change is included in the patch version increment

### ISSUE THREAD

**Issue by ysknkd** [AthenZ/athenz#2073]
Please let me confirm the versioning of Athenz.

From past commit #1160, it seems that there is a break change in [the patch versioning](https://github.com/AthenZ/athenz/releases/tag/v1.9.23).
It would be nice if the major version is incremented when there is a breaking change, could you please consider this?

**Comment by ysknkd** [comment]
Additionally, if it's possible, could you please revert this PR?

The reason is that the RDL defines that ZMS responds with `Array<MemberName> members` as Role, but in v1.9.23 and later, ZMS never responds with `members`, so there is a gap between the RDL and the implementation.

https://github.com/AthenZ/athenz/blob/71b535c296c1c7ac56d698e1a7591463b00a0c12/core/zms/src/main/rdl/Role.tdl#L60-L68

**Comment by havetisyan** [comment]
this was not considered as a breaking change, since the day one when athenz was opensourced, that attribute should not have been used and instead the correct role members attributes must be used. it's actually incorrect to use that attribute since the caller incorrectly assumes the role members that are listed there are valid yet they could be long expired.

how and why are you using that attribute?

**Comment by ysknkd** [comment]
Thanks for the reply.

I understand that `roleMembers` is best for managing members. I would be happy to see a comment in the RDL that `members` is deprecated and should not be used, could you please add it?

**Comment by ysknkd** [comment]
Thank you for describe that members is deprecated in the RDL.
