### ISSUE TITLE
Want to overwrite roles with zms-cli

### ISSUE THREAD

**Issue by ysknkd** [AthenZ/athenz#2171]
# Want to overwrite roles with zms-cli

The `add-regular-role` command in zms-cli performs a role duplication check, which prevents from overwriting a role with specified members.
https://github.com/AthenZ/athenz/blob/cc277fca14df6093d41df9252e32eefda7e3b4e8/libs/go/zmscli/role.go#L122-L125

Here is the current behavior:

```shell
$ zms-cli -d test-domain add-regular-role test-role user.alice user.bob

role:
    - name: test-role
      members:
        - name: user.alice
        - name: user.bob

$ zms-cli -d test-domain add-regular-role test-role user.carol user.charlie
*** role already exists: test-domain:role.test-role
```

I would like to have a feature that overwrites an existing role when a certain option is specified.

```shell
$ zms-cli -d test-domain add-regular-role test-role user.alice user.bob

role:
    - name: test-role
      members:
        - name: user.alice
        - name: user.bob

$ zms-cli -d test-domain -force=true add-regular-role test-role user.carol user.charlie

role:
    - name: test-role
      members:
        - name: user.carol 
        - name: user.charlie
```

Just out of curiosity, is the absence of such a feature due to the current policy of zms-cli?

**Comment by havetisyan** [comment]
If you're not careful, having such functionality could have un-intended results where admins may accidentally overwrite their roles with only a few members and thus cause some kind of outage. This is why we never added such a flag and nobody has requested it.

Additionally, you cannot overwrite roles that are either review-enabled or audit-enabled. If you have these flags set on a role, then you must use the the add/delete role member api commands.

But you're welcome to submit a PR to add such a flag - though I would use `-overwrite=true` instead of `-force=true` since overwrite clearly specifies the intention of the call. As I mentioned above, it will only be supported for roles without review/audit flags.

**Comment by ysknkd** [comment]
Thank you for your response.

I understand your explanation regarding the potential for unintended results and the restrictions on overwriting roles that are review-enabled or audit-enabled.

With your points in mind, I will proceed to create a PR using the -overwrite=true flag, taking care to ensure it only applies to roles without review/audit flags.
