### ISSUE TITLE
Handling Usernames with Dots Authenticated by External IdP

### ISSUE THREAD

**Issue by ysknkd** [AthenZ/athenz#2176]
Hello, I would appreciate any ideas on how to handle cases where Usernames, authenticated by an external IdP, contain dots.

As you may be aware, Athenz does not allow dots in Principal Names. In the current implementation of Athenz, if a Principal Name contains a dot, it interprets part of it as a domain.
https://github.com/AthenZ/athenz/blob/14d43f6b0ef9e53284d44448168a733ebf742d53/core/zms/src/main/rdl/Names.tdl#L8-L9

Ideally, it would be best to eliminate dots from the Username. However, if that is not possible, we are considering replacing the dots with a different character. For instance, a Username `yosuke.nakada` could be replaced with `yosuke_nakada`.

We anticipate the following changes, but would like to know if there are other ways to handle this in Athenz, especially when a Username inevitably contains dots:

* Replace the dot in the Username with another character when generating the Principal in Authority
* Replace the dot in the Username with another character when certain APIs are invoked. Specifically, the following APIs:
    * putRole
    * putRoleReview
    * putMembership
    * getDomainList
    * deletePendingMembership
    * getAccess
    * getAccessExt

**Comment by havetisyan** [comment]
I have to think about this a little bit more but I'm hoping you're not using the same domain for user and home domains. For example, user henry is identified as principal user.henry but has a home account as home.henry and not user.henry again.
I'm not a big fan of replacements but I'm thinking as long as we have a special domain reserved for users (e.g. user) then the logic to determine the principal is:

if the principal identity starts with user. (e.g. user.joe.smith) then it's domain is "user" and service is "joe.smith"
otherwise (e.g. sports.joe.smith we look for the . from the end and domain is "sports.joe" and service is "smith"
So the requirement with this is that all applications/api endpoints, etc when they do parsing of the principal, they're aware of the user domain and act accordingly. Server side should be straight forward and it's basically the clients need to be aware of the change and update accordingly. 

As far user's home domains are concerned, this is where we can introduce translation since it's just a domain name. So when joe.smith wants a home domain to test things about, the domain name would be home.joe-smith and joe-smith would become home.joe--smith (or some other translation method - it's just the generated home domains must be unique).

I'll think about this a little bit more but I think this is a better approach without replacing the identity in the Principal Authority.

**Comment by ysknkd** [comment]
Thank you for your response. I also believe that server implementation should remain simple and prefer not to make extensive modifications. I will consider using a different identifier included in the Token issued by the IdP. As for this matter, I will close it for now.
